export const frontEndSkills = [
  { skill: 'htm5' },
  { skill: 'css3' },
  { skill: 'javascipt' },
  { skill: 'ecmascript 6,7,8' },
  { skill: 'typescript' },
  { skill: 'react' },
  { skill: 'react native' },
  { skill: 'redux' },
  { skill: 'Next.js' },
  { skill: 'vue' },
  { skill: 'Angular' },
  { skill: 'pwa' },
  { skill: 'jquery' },
  { skill: 'sass' },
  { skill: 'bootstrap' },
  { skill: 'material-ui' },
  { skill: 'vuetify' },
  { skill: 'styled-components' },
  { skill: 'rx.js' },
  { skill: 'gulp' },
  { skill: 'webpack' },
  { skill: 'parcel' },
  { skill: 'ajax' },
  { skill: 'pixi.js' },
  { skill: 'phaser.js' },
]
export const backEndSkills = [
  { skill: 'node.js' },
  { skill: 'express.js' },
  { skill: 'GraphQl' },
  { skill: 'Apollo' },
  { skill: 'http/json' },
  { skill: 'api/rest' },
  { skill: 'ssh' },
  { skill: 'redis' },
  { skill: 'jwt' },
  { skill: 'docker' },
  { skill: 'knex.js' },
  { skill: 'postgresql' },
  { skill: 'mongodb' },
  { skill: 'jsreport' },
]

export const others = [
  {
    skill: 'Python',
  },
  {
    skill: 'Java',
  },
]
